apiVersion: apps/v1
kind: Deployment
metadata:
  name: tompeters-site
  labels:
    app: tompeters-site
spec:
  selector:
    matchLabels:
      app: tompeters-site
  template:
    metadata:
      labels:
        app: tompeters-site
    spec:
      containers:
      - name: tompeters-site
        image: ghcr.io/weters/tompeters-site/tompeters-site:latest
      imagePullSecrets:
      - name: github
